# Generated by Django 5.0.2 on 2024-03-13 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('body', models.CharField()),
                ('vision', models.CharField()),
                ('mission', models.CharField()),
                ('values', models.CharField()),
            ],
        ),
    ]
