# Generated by Django 5.0.2 on 2024-03-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('subtitle', models.TextField()),
                ('body', models.TextField()),
                ('discipleship', models.TextField()),
                ('development', models.TextField()),
                ('philosophy', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Page',
        ),
    ]
