# Generated by Django 5.0.2 on 2024-03-14 04:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField()),
                ('body', models.CharField()),
                ('vision', models.CharField()),
                ('mission', models.CharField()),
                ('values', models.CharField()),
            ],
        ),
    ]
