# Generated by Django 5.0.2 on 2024-03-15 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0002_remove_aboutpage_values_corevalues'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('values', models.TextField()),
                ('aboutpage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='aboutus.aboutpage')),
            ],
        ),
        migrations.DeleteModel(
            name='CoreValues',
        ),
    ]
