# Generated by Django 5.0.2 on 2024-03-20 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0003_corevalue_delete_corevalues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corevalue',
            name='values',
            field=models.CharField(),
        ),
    ]
