# Generated by Django 5.0.2 on 2024-03-29 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0005_aboutpage_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='position',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
