# Generated by Django 5.0.2 on 2024-04-01 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0007_remove_aboutpage_name_remove_aboutpage_position_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='staffPhotos/')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('position', models.CharField(blank=True, max_length=40)),
            ],
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='names',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='positions',
        ),
    ]
