# Generated by Django 5.0.2 on 2024-03-18 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField()),
                ('last_name', models.CharField()),
                ('message', models.TextField()),
                ('email', models.CharField()),
                ('telephone', models.CharField()),
                ('location', models.CharField()),
            ],
        ),
    ]
