# Generated by Django 5.0.2 on 2024-03-18 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpage',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
